//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cartridzhi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cartridzhi()
        {
            this.Table_2 = new HashSet<Table_2>();
        }
    
        public int id_cart { get; set; }
        public string Model { get; set; }
        public string Type_model { get; set; }
        public string Type_printer { get; set; }
        public string Amount { get; set; }
        public Nullable<int> id_printer { get; set; }
    
        public virtual Printer Printer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_2> Table_2 { get; set; }
    }
}
